const allWorkoutPlans = {
    A: {
        1: {
            title: "Chest, Shoulders & Triceps (Push)",
            warmup: "5 mins light cardio, dynamic stretches (arm circles, shoulder rolls), activation (band pull-aparts, wall slides).",
            exercises: [
                { name: "Barbell Bench Press", sets: "4", reps: "8-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie flat on a bench. Your feet should be planted firmly on the floor. Grip the barbell with your hands slightly wider than shoulder-width apart. Retract your shoulder blades by squeezing them together and down, creating a slight arch in your lower back. Your butt, shoulders, and head should be firmly on the bench.</li><li><strong>Execution:</strong> Unrack the bar and hold it directly over your mid-chest with your arms locked. Inhale and slowly lower the bar until it lightly touches your chest. Your elbows should be at about a 45-degree angle to your body, not flared out to the sides.</li><li><strong>Push:</strong> Exhale and press the bar back up to the starting position, driving through your chest and triceps. Focus on the bar path moving straight up and slightly back.</li></ul>" },
                { name: "Overhead Press (Standing)", sets: "4", reps: "8-10", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet shoulder-width apart. Hold a barbell at your front shoulders, with your hands just outside your shoulders, palms facing forward. Keep your core tight to stabilize your spine.</li><li><strong>Execution:</strong> Exhale and press the barbell straight up overhead until your arms are fully extended. Don't lean back excessively. Your head should move slightly back as the bar passes your face and then return to a neutral position once the bar is overhead.</li><li><strong>Return:</strong> Inhale and slowly lower the bar back to your shoulders under control.</li></ul>" },
                { name: "Incline Dumbbell Press", sets: "3", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set an adjustable bench to a 30-45 degree incline. Sit on the bench holding a dumbbell in each hand, resting them on your thighs. Lie back and bring the dumbbells up to the sides of your chest.</li><li><strong>Execution:</strong> Press the dumbbells up and together until your arms are fully extended, but don't clank them together at the top.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbells back to the starting position with a full range of motion, feeling a stretch in your chest.</li></ul>" },
                { name: "Dumbbell Lateral Raises", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with a dumbbell in each hand at your sides, palms facing in. Have a slight bend in your elbows and lean your torso slightly forward.</li><li><strong>Execution:</strong> Exhale and lift the dumbbells out to your sides until they are at shoulder height. Imagine you're pouring a jug of water. Your arms should be almost straight.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbells back to the starting position with control.</li></ul>" },
                { name: "Close-Grip Bench Press", sets: "3", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie on a flat bench just like a regular bench press, but grip the bar with your hands about shoulder-width apart.</li><li><strong>Execution:</strong> Lower the bar to your lower chest, keeping your elbows tucked close to your body. This is crucial for targeting the triceps.</li><li><strong>Push:</strong> Exhale and press the bar back up, focusing on the contraction in your triceps.</li></ul>" },
                { name: "Dumbbell Overhead Tricep Extension", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> You can do this seated or standing. Hold one dumbbell with both hands, cupping the top end. Raise it directly overhead.</li><li><strong>Execution:</strong> Keeping your upper arms stationary and close to your head, inhale and lower the dumbbell behind your head by bending your elbows.</li><li><strong>Extend:</strong> Exhale and extend your arms to raise the dumbbell back to the starting position.</li></ul>" },
            ],
            cooldown: "Static stretching for chest, shoulders, and triceps."
        },
        2: {
            title: "Back & Biceps (Pull)",
            warmup: "Joint mobility, light cardio, band pull-aparts, and scapular wall slides.",
            exercises: [
                { name: "Deadlifts", sets: "4", reps: "5", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet hip-width apart, with the middle of your feet under the barbell. Hinge at your hips and bend your knees to grip the bar just outside your shins. Keep your back straight (neutral spine) and your chest up.</li><li><strong>Execution:</strong> Inhale, tighten your core, and drive through your heels to lift the weight. The bar should stay close to your body the entire time. As the bar passes your knees, thrust your hips forward to stand up straight. Squeeze your glutes at the top.</li><li><strong>Return:</strong> Reverse the motion by hinging at the hips first, then bending your knees once the bar is past them. Maintain a flat back throughout.</li></ul>" },
                { name: "Barbell Bent-Over Rows", sets: "4", reps: "8-10", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with feet shoulder-width apart. Hinge at your hips until your torso is nearly parallel to the floor, maintaining a flat back. Grip the barbell with an overhand grip, slightly wider than your shoulders.</li><li><strong>Execution:</strong> Exhale and pull the barbell up towards your lower chest. Squeeze your shoulder blades together at the top of the movement.</li><li><strong>Return:</strong> Inhale and slowly lower the bar back to the starting position.</li></ul>" },
                { name: "Lat Pulldowns", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit at a lat pulldown machine and adjust the knee pad to be snug. Grip the bar with a wide, overhand grip. Lean back slightly.</li><li><strong>Execution:</strong> Exhale and pull the bar down to your upper chest. Focus on using your back muscles (lats) to initiate the pull, not just your arms.</li><li><strong>Return:</strong> Inhale and slowly control the bar as it returns to the starting position.</li></ul>" },
                { name: "Chest-Supported Dumbbell Rows", sets: "3", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set an incline bench to about 45 degrees. Lie face down on the bench with a dumbbell in each hand, arms extended towards the floor.</li><li><strong>Execution:</strong> Exhale and row the dumbbells up towards your hips. Squeeze your shoulder blades together and pause briefly at the top.</li><li><strong>Return:</strong> Inhale and lower the dumbbells back down with control.</li></ul>" },
                { name: "Barbell Bicep Curls", sets: "3", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand straight, holding a barbell with an underhand grip, hands shoulder-width apart. Your elbows should be close to your sides.</li><li><strong>Execution:</strong> Exhale and curl the barbell up towards your shoulders, keeping your elbows stationary. Avoid swinging your body.</li><li><strong>Return:</strong> Inhale and slowly lower the barbell back to the starting position for a full range of motion.</li></ul>" },
                { name: "Hammer Curls", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand holding a dumbbell in each hand with a neutral grip (palms facing each other), like you're holding a hammer.</li><li><strong>Execution:</strong> Exhale and curl one dumbbell up towards your shoulder, keeping your palm facing in.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbell. Alternate arms with each rep.</li></ul>" },
            ],
            cooldown: "Static stretching for back and biceps."
        },
        3: {
            title: "Legs & Glutes",
            warmup: "Hip circles, leg swings, glute bridges, and bodyweight squats for movement prep.",
            exercises: [
                { name: "Barbell Back Squats", sets: "4", reps: "8-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Place a barbell on a rack at about shoulder height. Step under it and rest the bar across your upper back (on your traps, not your neck). Grip the bar firmly. Stand with your feet shoulder-width apart, toes pointing slightly out.</li><li><strong>Execution:</strong> Inhale, keep your chest up, and brace your core. Begin the squat by pushing your hips back and then bending your knees, as if sitting in a chair. Go down until your hip crease is below your knees (if mobility allows). Ensure your knees track in line with your toes.</li><li><strong>Ascend:</strong> Exhale and drive through your heels to return to a standing position.</li></ul>" },
                { name: "Romanian Deadlifts (RDLs)", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand holding a barbell or dumbbells in front of your thighs. Your feet should be hip-width apart.</li><li><strong>Execution:</strong> Keeping your legs relatively straight (a slight bend in the knees is okay), hinge at your hips and lower the weight towards the floor. Keep your back straight and the weight close to your legs. You should feel a deep stretch in your hamstrings.</li><li><strong>Return:</strong> Squeeze your glutes and hamstrings to pull your torso back up to the starting position.</li></ul>" },
                { name: "Bulgarian Split Squats", sets: "3", reps: "10-12 per leg", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand a few feet in front of a bench. Place the top of one foot on the bench behind you. Hold dumbbells in each hand if you're using weight.</li><li><strong>Execution:</strong> Inhale and lower your body until your front thigh is parallel to the floor. Your torso should remain upright, and your front knee should not go past your toes.</li><li><strong>Ascend:</strong> Exhale and drive through the heel of your front foot to return to the starting position. Complete all reps for one leg before switching.</li></ul>" },
                { name: "Walking Lunges", sets: "3", reps: "12-15 per leg", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet together.</li><li><strong>Execution:</strong> Take a large step forward with one leg. Lower your hips until both knees are bent at a 90-degree angle. Your front knee should be above your ankle, and your back knee should hover just above the ground.</li><li><strong>Step Through:</strong> Push off your back foot and drive through the heel of your front foot to bring your back foot forward, stepping directly into the next lunge with the opposite leg.</li></ul>" },
                { name: "Leg Press", sets: "3", reps: "15-20", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on the leg press machine with your back and head flat against the pad. Place your feet on the platform shoulder-width apart.</li><li><strong>Execution:</strong> Push the platform away from you by extending your knees. At the top, your legs should be almost straight, but not locked.</li><li><strong>Return:</strong> Inhale and slowly bend your knees to return the platform to the starting position, maintaining control.</li></ul>" },
                { name: "Standing Calf Raises", sets: "4", reps: "15-20", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand on a raised surface (like a step or weight plate) with the balls of your feet on the edge and your heels hanging off.</li><li><strong>Execution:</strong> Allow your heels to drop down to get a full stretch in your calves. Then, push through the balls of your feet to raise your heels as high as possible, pausing at the top to squeeze your calf muscles.</li><li><strong>Return:</strong> Slowly lower your heels back down.</li></ul>" },
            ],
            cooldown: "Static stretching for hamstrings, quads, and glutes."
        },
        4: {
            title: "Chest, Shoulders & Triceps (Volume)",
            warmup: "5 mins light cardio, dynamic stretches (arm circles, shoulder rolls), activation (band pull-aparts, wall slides).",
            exercises: [
                { name: "Dumbbell Bench Press", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie on a flat bench holding a dumbbell in each hand, resting them on your thighs. Lie back and use your thighs to help \"kick\" the dumbbells up to the starting position at the sides of your chest. Plant your feet firmly on the floor.</li><li><strong>Execution:</strong> Exhale and press the dumbbells straight up until your arms are fully extended over your chest. Unlike a barbell, you have a greater range of motion, so focus on a good squeeze at the top.</li><li><strong>Return:</strong> Inhale and slowly lower the weights back to the sides of your chest, feeling a stretch in your pectoral muscles.</li></ul>" },
                { name: "Dumbbell Shoulder Press (Seated)", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on a bench with back support. Hold a dumbbell in each hand at shoulder height, palms facing forward, and elbows bent at a 90-degree angle.</li><li><strong>Execution:</strong> Exhale and press the dumbbells straight overhead until your arms are fully extended. Don't arch your back excessively; keep it pressed against the bench.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbells back to the starting position.</li></ul>" },
                { name: "Push-ups", sets: "3", reps: "To near failure", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Get into a high plank position with your hands directly under your shoulders, your body in a straight line from your head to your heels. Engage your core and glutes.</li><li><strong>Execution:</strong> Inhale and lower your body by bending your elbows. Keep them tucked at about a 45-degree angle to your body. Go down until your chest is just above the floor.</li><li><strong>Push:</strong> Exhale and push through your palms to return to the starting position.</li><li><strong>Modification:</strong> If this is too hard, perform them on your knees or with your hands on an elevated surface (like a bench).</li></ul>" },
                { name: "Cable Lateral Raises", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand sideways next to a cable machine with the pulley set to the lowest position. Hold the handle with the hand farthest from the machine.</li><li><strong>Execution:</strong> Keeping your arm mostly straight (a slight bend in the elbow is fine), raise your arm out to the side until it's at shoulder height.</li><li><strong>Return:</strong> Slowly lower the handle back to the starting position with control. This provides constant tension, which is great for muscle growth.</li></ul>" },
                { name: "Dips", sets: "3", reps: "8-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Use parallel bars. Grip the bars and push yourself up until your arms are locked. Lean your torso slightly forward to target the chest more; keep it upright to target the triceps more.</li><li><strong>Execution:</strong> Inhale and lower your body by bending your elbows until your shoulders are slightly below your elbows.</li><li><strong>Push:</strong> Exhale and press through your palms to return to the starting position.</li><li><strong>Modification:</strong> If this is too hard, use an assisted dip machine or do bench dips with your feet on the floor.</li></ul>" },
                { name: "Cable Tricep Pushdowns", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Attach a straight bar or rope to a high pulley on a cable machine. Stand facing the machine, grab the attachment with an overhand grip, and pull it down until your elbows are at your sides, bent at 90 degrees.</li><li><strong>Execution:</strong> Exhale and push the bar down until your arms are fully extended. Keep your elbows pinned to your sides; only your forearms should move.</li><li><strong>Return:</strong> Inhale and slowly return to the 90-degree starting position.</li></ul>" },
            ],
            cooldown: "Static stretching for chest, shoulders, and triceps."
        },
        5: {
            title: "Back & Biceps (Volume)",
            warmup: "Joint mobility, light cardio, band pull-aparts, and scapular wall slides.",
            exercises: [
                { name: "T-Bar Rows", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Place one end of an empty barbell into a corner or a landmine attachment. Load the other end with weight. Stand over the bar with a foot on each side. Hinge at your hips and grab the handle attachment under the bar. Keep your back straight.</li><li><strong>Execution:</strong> Exhale and pull the weight up towards your lower chest, squeezing your back muscles.</li><li><strong>Return:</strong> Inhale and slowly lower the weight back down without letting it touch the floor.</li></ul>" },
                { name: "Wide-Grip Lat Pulldowns", sets: "4", reps: "8-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit at a lat pulldown machine and adjust the knee pad to be snug. Grip the bar with a wide, overhand grip. Lean back slightly.</li><li><strong>Execution:</strong> Exhale and pull the bar down to your upper chest. Focus on using your back muscles (lats) to initiate the pull, not just your arms.</li><li><strong>Return:</strong> Inhale and slowly control the bar as it returns to the starting position.</li></ul>" },
                { name: "Cable Rows (Seated)", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit at a cable row machine with your feet on the platforms and knees slightly bent. Sit up tall with your back straight. Grab the V-bar handle.</li><li><strong>Execution:</strong> Exhale and pull the handle towards your lower abdomen. Squeeze your shoulder blades together.</li><li><strong>Return:</strong> Inhale and slowly extend your arms, allowing your shoulder blades to stretch forward without rounding your back.</li></ul>" },
                { name: "Single-Arm Dumbbell Rows", sets: "3", reps: "10-12 per arm", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Place your left knee and left hand on a flat bench for support. Your back should be flat and parallel to the floor. Hold a dumbbell in your right hand with your arm extended.</li><li><strong>Execution:</strong> Exhale and pull the dumbbell up towards your hip. Keep your elbow close to your body and focus on using your back muscles.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbell back down. Complete all reps on one side before switching.</li></ul>" },
                { name: "Preacher Curls", sets: "3", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit at a preacher curl bench, adjusting the seat so your armpits are near the top of the pad. Rest the back of your upper arms on the pad. Hold an EZ-bar or dumbbells with an underhand grip.</li><li><strong>Execution:</strong> Exhale and curl the weight up. Because your arms are supported, you can't cheat, which isolates the biceps.</li><li><strong>Return:</strong> Inhale and slowly lower the weight until your arms are fully extended, feeling a stretch in your biceps.</li></ul>" },
                { name: "Cable Hammer Curls", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Attach a rope handle to a low pulley. Stand facing the machine and grab the rope with a neutral (hammer) grip.</li><li><strong>Execution:</strong> Exhale and curl the rope up, keeping your elbows at your sides. The constant tension from the cable makes this a great finisher.</li><li><strong>Return:</strong> Inhale and slowly lower the rope back to the start.</li></ul>" },
            ],
            cooldown: "Static stretching for back and biceps."
        },
        6: {
            title: "Legs & Core",
            warmup: "Hip circles, leg swings, glute bridges, and bodyweight squats.",
            exercises: [
                { name: "Front Squats", sets: "4", reps: "8-10", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set the barbell in a rack at shoulder height. Step up to it and rest the bar across the front of your shoulders. You can use a \"clean grip\" (fingers under the bar) or a \"cross-arm grip\" (arms crossed over the bar). Keep your elbows high and your torso upright.</li><li><strong>Execution:</strong> Squat down just like a back squat, focusing on keeping your chest up and elbows high. The weight position forces you to stay more upright, which targets the quads more and is often safer for the lower back.</li><li><strong>Ascend:</strong> Drive through your heels to stand back up.</li></ul>" },
                { name: "Stiff-Leg Deadlifts", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand holding a barbell or dumbbells in front of your thighs. Your feet should be hip-width apart.</li><li><strong>Execution:</strong> Keeping your legs relatively straight (a slight bend in the knees is okay), hinge at your hips and lower the weight towards the floor. Keep your back straight and the weight close to your legs. You should feel a deep stretch in your hamstrings.</li><li><strong>Return:</strong> Squeeze your glutes and hamstrings to pull your torso back up to the starting position.</li></ul>" },
                { name: "Leg Curls (Lying or Seated)", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> On a lying leg curl machine, lie face down and place the back of your lower legs under the padded lever. On a seated machine, sit and place the front of your lower legs behind the pad.</li><li><strong>Execution:</strong> Exhale and curl the weight up towards your glutes (lying) or down towards the floor (seated) by contracting your hamstrings.</li><li><strong>Return:</strong> Inhale and slowly lower the weight back to the starting position.</li></ul>" },
                { name: "Leg Extensions", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on a leg extension machine with your back against the pad and the front of your shins tucked behind the padded bar.</li><li><strong>Execution:</strong> Exhale and extend your legs until they are straight out in front of you, squeezing your quadriceps at the top.</li><li><strong>Return:</strong> Inhale and slowly lower the weight back down.</li></ul>" },
                { name: "Planks", sets: "3", reps: "30-60 seconds", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie on your stomach and prop yourself up on your forearms and toes. Your elbows should be directly under your shoulders.</li><li><strong>Execution:</strong> Keep your body in a perfectly straight line from head to heels. Engage your core and glutes. Don't let your hips sag or rise too high. Hold this position for the prescribed time.</li></ul>" },
                { name: "Russian Twists", sets: "3", reps: "20-30 total", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on the floor, lean back slightly, and lift your feet off the ground. You can hold a weight plate or dumbbell for more resistance.</li><li><strong>Execution:</strong> Twist your torso from side to side, touching the weight to the floor on each side of your hips. Keep the movement controlled.</li></ul>" },
            ],
            cooldown: "Stretching for legs and core."
        },
        7: { title: "Rest Day", warmup: "", exercises: [], cooldown: "Focus on recovery: light stretching, mobility work, hydration, and proper nutrition. Your muscles grow and repair when you rest." },
    },
    B: {
        1: {
            title: "Upper Body Push - Hypertrophy Focus",
            warmup: "Joint mobility, activation (band pull-aparts, wall slides), dynamic prep (push-up progressions).",
            exercises: [
                { name: "Barbell Bench Press", sets: "4", reps: "6-8", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie flat on a bench. Your feet should be planted firmly on the floor. Grip the barbell with your hands slightly wider than shoulder-width apart. Retract your shoulder blades by squeezing them together and down, creating a slight arch in your lower back. Your butt, shoulders, and head should be firmly on the bench.</li><li><strong>Execution:</strong> Unrack the bar and hold it directly over your mid-chest with your arms locked. Inhale and slowly lower the bar until it lightly touches your chest. Your elbows should be at about a 45-degree angle to your body, not flared out to the sides.</li><li><strong>Push:</strong> Exhale and press the bar back up to the starting position, driving through your chest and triceps. Focus on the bar path moving straight up and slightly back.</li></ul>" },
                { name: "Incline Dumbbell Press", sets: "4", reps: "8-10", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set an adjustable bench to a 30-45 degree incline. Sit on the bench holding a dumbbell in each hand, resting them on your thighs. Lie back and bring the dumbbells up to the sides of your chest.</li><li><strong>Execution:</strong> Press the dumbbells up and together until your arms are fully extended, but don't clank them together at the top.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbells back to the starting position with a full range of motion, feeling a stretch in your chest.</li></ul>" },
                { name: "Dumbbell Shoulder Press", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on a bench with back support. Hold a dumbbell in each hand at shoulder height, palms facing forward, and elbows bent at a 90-degree angle.</li><li><strong>Execution:</strong> Exhale and press the dumbbells straight overhead until your arms are fully extended. Don't arch your back excessively; keep it pressed against the bench.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbells back to the starting position.</li></ul>" },
                { name: "Lateral Raise Cluster Sets", sets: "3", reps: "8+8+8", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with a dumbbell in each hand at your sides, palms facing in. Have a slight bend in your elbows and lean your torso slightly forward.</li><li><strong>Execution:</strong> Exhale and lift the dumbbells out to your sides until they are at shoulder height. A cluster set means you do 8 reps, rest for a very short period (e.g., 30 seconds), do another 8 reps, rest again, and do a final 8 reps. This is one full set.</li><li><strong>Return:</strong> Inhale and slowly lower the dumbbells back to the starting position with control.</li></ul>" },
                { name: "Close-Grip Bench Press", sets: "3", reps: "8-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie on a flat bench just like a regular bench press, but grip the bar with your hands about shoulder-width apart.</li><li><strong>Execution:</strong> Lower the bar to your lower chest, keeping your elbows tucked close to your body. This is crucial for targeting the triceps.</li><li><strong>Push:</strong> Exhale and press the bar back up, focusing on the contraction in your triceps.</li></ul>" },
                { name: "Tricep Dips", sets: "3", reps: "10-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Use parallel bars. Grip the bars and push yourself up until your arms are locked. Keep your torso upright to target the triceps.</li><li><strong>Execution:</strong> Inhale and lower your body by bending your elbows until your shoulders are slightly below your elbows.</li><li><strong>Push:</strong> Exhale and press through your palms to return to the starting position.</li></ul>" },
            ],
            cooldown: "Static stretching for chest, shoulders, and triceps."
        },
        2: {
            title: "Lower Body Power & Strength",
            warmup: "Hip circles, leg swings, glute activation, bodyweight squats, lunges.",
            exercises: [
                { name: "Barbell Back Squat", sets: "5", reps: "5", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Place a barbell on a rack at about shoulder height. Step under it and rest the bar across your upper back (on your traps, not your neck). Grip the bar firmly. Stand with your feet shoulder-width apart, toes pointing slightly out.</li><li><strong>Execution:</strong> Inhale, keep your chest up, and brace your core. Begin the squat by pushing your hips back and then bending your knees, as if sitting in a chair. Go down until your hip crease is below your knees (if mobility allows). Ensure your knees track in line with your toes.</li><li><strong>Ascend:</strong> Exhale and drive through your heels to return to a standing position.</li></ul>" },
                { name: "Romanian Deadlifts", sets: "4", reps: "6-8", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand holding a barbell or dumbbells in front of your thighs. Your feet should be hip-width apart.</li><li><strong>Execution:</strong> Keeping your legs relatively straight (a slight bend in the knees is okay), hinge at your hips and lower the weight towards the floor. Keep your back straight and the weight close to your legs. You should feel a deep stretch in your hamstrings.</li><li><strong>Return:</strong> Squeeze your glutes and hamstrings to pull your torso back up to the starting position.</li></ul>" },
                { name: "Bulgarian Split Squats", sets: "4", reps: "10-12 per leg", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand a few feet in front of a bench. Place the top of one foot on the bench behind you. Hold dumbbells in each hand if you're using weight.</li><li><strong>Execution:</strong> Inhale and lower your body until your front thigh is parallel to the floor. Your torso should remain upright, and your front knee should not go past your toes.</li><li><strong>Ascend:</strong> Exhale and drive through the heel of your front foot to return to the starting position. Complete all reps for one leg before switching.</li></ul>" },
                { name: "Hip Thrusts", sets: "4", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on the floor with your upper back against the side of a flat bench. Place a barbell across your hips (use a pad for comfort). Your feet should be flat on the floor, shoulder-width apart, with your knees bent.</li><li><strong>Execution:</strong> Drive through your heels and squeeze your glutes to lift your hips towards the ceiling until your body forms a straight line from your shoulders to your knees.</li><li><strong>Return:</strong> Slowly lower your hips back down.</li></ul>" },
                { name: "Walking Lunges", sets: "3", reps: "12-15 per leg", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet together.</li><li><strong>Execution:</strong> Take a large step forward with one leg. Lower your hips until both knees are bent at a 90-degree angle. Your front knee should be above your ankle, and your back knee should hover just above the ground.</li><li><strong>Step Through:</strong> Push off your back foot and drive through the heel of your front foot to bring your back foot forward, stepping directly into the next lunge with the opposite leg.</li></ul>" },
                { name: "Standing Calf Raises", sets: "4", reps: "15-20", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand on a raised surface (like a step or weight plate) with the balls of your feet on the edge and your heels hanging off.</li><li><strong>Execution:</strong> Allow your heels to drop down to get a full stretch in your calves. Then, push through the balls of your feet to raise your heels as high as possible, pausing at the top to squeeze your calf muscles.</li><li><strong>Return:</strong> Slowly lower your heels back down.</li></ul>" },
            ],
            cooldown: "Static stretching for hamstrings, quads, and glutes."
        },
        3: {
            title: "Upper Body Pull - Hypertrophy Focus",
            warmup: "Joint mobility, activation (band pull-aparts, wall slides), dynamic prep.",
            exercises: [
                { name: "Barbell Bent-Over Rows", sets: "4", reps: "6-8", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with feet shoulder-width apart. Hinge at your hips until your torso is nearly parallel to the floor, maintaining a flat back. Grip the barbell with an overhand grip, slightly wider than your shoulders.</li><li><strong>Execution:</strong> Exhale and pull the barbell up towards your lower chest. Squeeze your shoulder blades together at the top of the movement.</li><li><strong>Return:</strong> Inhale and slowly lower the bar back to the starting position.</li></ul>" },
                { name: "Lat Pulldowns", sets: "4", reps: "8-10", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit at a lat pulldown machine and adjust the knee pad to be snug. Grip the bar with a wide, overhand grip. Lean back slightly.</li><li><strong>Execution:</strong> Exhale and pull the bar down to your upper chest. Focus on using your back muscles (lats) to initiate the pull, not just your arms.</li><li><strong>Return:</strong> Inhale and slowly control the bar as it returns to the starting position.</li></ul>" },
                { name: "Chest-Supported Dumbbell Rows", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set an incline bench to about 45 degrees. Lie face down on the bench with a dumbbell in each hand, arms extended towards the floor.</li><li><strong>Execution:</strong> Exhale and row the dumbbells up towards your hips. Squeeze your shoulder blades together and pause briefly at the top.</li><li><strong>Return:</strong> Inhale and lower the dumbbells back down with control.</li></ul>" },
                { name: "Cable Face Pulls", sets: "4", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Attach a rope handle to a high pulley. Grab the ropes with an overhand grip, palms facing down. Step back so there's tension on the cable.</li><li><strong>Execution:</strong> Pull the rope towards your face, aiming for your nose/forehead. As you pull, separate your hands and externally rotate your shoulders (think \"bicep flex\" pose). Squeeze your upper back muscles.</li><li><strong>Return:</strong> Slowly extend your arms back to the starting position. This is a crucial exercise for shoulder health.</li></ul>" },
                { name: "Barbell Bicep Curls", sets: "3", reps: "8-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand straight, holding a barbell with an underhand grip, hands shoulder-width apart. Your elbows should be close to your sides.</li><li><strong>Execution:</strong> Exhale and curl the barbell up towards your shoulders, keeping your elbows stationary. Avoid swinging your body.</li><li><strong>Return:</strong> Inhale and slowly lower the barbell back to the starting position for a full range of motion.</li></ul>" },
                { name: "Cable Reverse Flyes", sets: "2", reps: "15-20", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set the pulleys on a cable crossover machine to about chest height. Grab the left handle with your right hand and the right handle with your left hand. Step back.</li><li><strong>Execution:</strong> With a slight bend in your elbows, pull your arms out and back in a wide arc, squeezing your shoulder blades together.</li><li><strong>Return:</strong> Slowly return to the start, controlling the weight.</li></ul>" },
            ],
            cooldown: "Static stretching for back and biceps."
        },
        4: {
            title: "Lower Body Hypertrophy & Glutes",
            warmup: "Hip circles, leg swings, glute activation, bodyweight squats.",
            exercises: [
                { name: "Goblet Squats", sets: "4", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet slightly wider than shoulder-width. Hold a single dumbbell or kettlebell vertically against your chest with both hands, cupping the top end.</li><li><strong>Execution:</strong> Keeping the weight at your chest, squat down by pushing your hips back. The weight acts as a counterbalance, making it easier to keep your torso upright and squat deep.</li><li><strong>Ascend:</strong> Drive through your heels to return to the start.</li></ul>" },
                { name: "Single-Leg Romanian Deadlifts", sets: "4", reps: "8-10 per leg", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand on one leg while holding a dumbbell in the opposite hand.</li><li><strong>Execution:</strong> Hinge at your hip, extending your non-standing leg straight behind you for balance. Lower the dumbbell towards the ground, keeping your back flat.</li><li><strong>Return:</strong> Squeeze your glute and hamstring to return to the starting position. This is excellent for balance and stability.</li></ul>" },
                { name: "Leg Curls", sets: "3", reps: "12-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> On a lying leg curl machine, lie face down and place the back of your lower legs under the padded lever. On a seated machine, sit and place the front of your lower legs behind the pad.</li><li><strong>Execution:</strong> Exhale and curl the weight up towards your glutes (lying) or down towards the floor (seated) by contracting your hamstrings.</li><li><strong>Return:</strong> Inhale and slowly lower the weight back to the starting position.</li></ul>" },
                { name: "Leg Extensions", sets: "3", reps: "15-20", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Sit on a leg extension machine with your back against the pad and the front of your shins tucked behind the padded bar.</li><li><strong>Execution:</strong> Exhale and extend your legs until they are straight out in front of you, squeezing your quadriceps at the top.</li><li><strong>Return:</strong> Inhale and slowly lower the weight back down.</li></ul>" },
                { name: "Glute Bridges", sets: "4", reps: "15-20", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie on your back with your knees bent and feet flat on the floor, hip-width apart.</li><li><strong>Execution:</strong> Squeeze your glutes and lift your hips off the floor until your body forms a straight line from your shoulders to your knees. Pause and squeeze at the top.</li><li><strong>Return:</strong> Slowly lower your hips back to the floor.</li></ul>" },
                { name: "Lateral Lunges (Side Lunges)", sets: "3", reps: "10-12 per side", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet together.</li><li><strong>Execution:</strong> Take a large step out to one side. Bend the knee of your stepping leg and push your hips back, keeping your other leg straight. Your torso will lean forward slightly, but keep your back flat.</li><li><strong>Return:</strong> Push off your bent leg to return to the starting position. Alternate sides.</li></ul>" },
                { name: "Wall Sit", sets: "3", reps: "30-45 seconds", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your back against a wall.</li><li><strong>Execution:</strong> Slide down the wall until your thighs are parallel to the floor, as if you're sitting in an invisible chair. Your knees should be at a 90-degree angle and directly above your ankles. Hold this position.</li></ul>" },
            ],
            cooldown: "Static stretching for legs and glutes."
        },
        5: {
            title: "Full Body Compound Strength",
            warmup: "Full body dynamic movements, activation for major muscle groups.",
            exercises: [
                { name: "Deadlifts", sets: "5", reps: "3-5", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with your feet hip-width apart, with the middle of your feet under the barbell. Hinge at your hips and bend your knees to grip the bar just outside your shins. Keep your back straight (neutral spine) and your chest up.</li><li><strong>Execution:</strong> Inhale, tighten your core, and drive through your heels to lift the weight. The bar should stay close to your body the entire time. As the bar passes your knees, thrust your hips forward to stand up straight. Squeeze your glutes at the top.</li><li><strong>Return:</strong> Reverse the motion by hinging at the hips first, then bending your knees once the bar is past them. Maintain a flat back throughout.</li></ul>" },
                { name: "Front Squats", sets: "4", reps: "6-8", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set the barbell in a rack at shoulder height. Step up to it and rest the bar across the front of your shoulders. You can use a \"clean grip\" (fingers under the bar) or a \"cross-arm grip\" (arms crossed over the bar). Keep your elbows high and your torso upright.</li><li><strong>Execution:</strong> Squat down just like a back squat, focusing on keeping your chest up and elbows high.</li><li><strong>Ascend:</strong> Drive through your heels to stand back up.</li></ul>" },
                { name: "Inverted Rows", sets: "4", reps: "10-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Set a barbell in a squat rack at about hip height. Lie on the floor underneath the bar. Grab the bar with an overhand, shoulder-width grip. Your body should be a straight line.</li><li><strong>Execution:</strong> Pull your chest up to the bar, squeezing your shoulder blades together.</li><li><strong>Return:</strong> Slowly lower yourself back down.</li></ul>" },
                { name: "Turkish Get-Ups", sets: "3", reps: "5 per side", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Lie on your back. Hold a kettlebell or dumbbell in your right hand, arm extended straight up. Your right knee should be bent, foot flat on the floor. Your left arm and leg should be out to the side at a 45-degree angle.</li><li><strong>Execution:</strong> (1) Push off your right foot and roll onto your left forearm. (2) Push up to your left hand. (3) Lift your hips off the floor. (4) Sweep your left leg back and under your body into a kneeling position. (5) Come to an upright lunge position. (6) Stand up.</li><li><strong>Return:</strong> Reverse the entire sequence step-by-step to lie back down. Keep your eyes on the weight the entire time.</li></ul>" },
                { name: "Farmer's Walks", sets: "3", reps: "30-40 steps", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Hold a heavy dumbbell or kettlebell in each hand at your sides.</li><li><strong>Execution:</strong> Stand up tall, pull your shoulders back, and brace your core. Walk for a set distance or time, taking controlled steps.</li></ul>" },
                { name: "Push-ups", sets: "4", reps: "8-15", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Get into a high plank position with your hands directly under your shoulders, your body in a straight line from your head to your heels. Engage your core and glutes.</li><li><strong>Execution:</strong> Inhale and lower your body by bending your elbows. Keep them tucked at about a 45-degree angle to your body. Go down until your chest is just above the floor.</li><li><strong>Push:</strong> Exhale and push through your palms to return to the starting position.</li></ul>" },
            ],
            cooldown: "Full body static stretching."
        },
        6: {
            title: "Functional Power & Weak Points",
            warmup: "Dynamic movements focusing on explosive power.",
            exercises: [
                { name: "Squat to Press (Thruster)", sets: "4", reps: "8-10", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Hold two dumbbells or a barbell in the \"front squat\" or \"front rack\" position at your shoulders.</li><li><strong>Execution:</strong> Perform a full front squat. As you explode up from the bottom of the squat, use that momentum to drive the weight directly overhead into a shoulder press. The movement should be fluid and explosive.</li><li><strong>Return:</strong> Lower the weight back to your shoulders and immediately descend into the next squat.</li></ul>" },
                { name: "Medicine Ball Slams", sets: "4", reps: "10-12", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand with feet shoulder-width apart, holding a medicine ball.</li><li><strong>Execution:</strong> Raise the ball overhead, rising onto your toes. Then, use your entire body (lats, core, glutes) to slam the ball into the ground in front of you as hard as you can.</li><li><strong>Return:</strong> Squat down to pick up the ball and repeat.</li></ul>" },
                { name: "Box Step-Ups (Explosive)", sets: "3", reps: "8-10 per leg", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand in front of a sturdy box or bench.</li><li><strong>Execution:</strong> Step up onto the box with your right foot, pressing through your right heel to straighten your leg. The focus is on driving up onto the box as quickly and forcefully as possible.</li><li><strong>Return:</strong> Step down with your left foot, then your right. You can alternate which leg leads with each rep.</li></ul>" },
                { name: "Battle Ropes", sets: "3", reps: "30 seconds", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand in an athletic stance (knees bent, back straight) holding the end of a heavy rope in each hand.</li><li><strong>Execution:</strong> Whip your arms up and down one at a time to send waves down the ropes. Keep your core tight and maintain the motion for the prescribed time.</li></ul>" },
                { name: "Medicine Ball Rotational Throws", sets: "3", reps: "8 per side", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Stand a few feet away from a solid wall, sideways. Hold a medicine ball with both hands at your hip farthest from the wall.</li><li><strong>Execution:</strong> In one explosive motion, rotate your hips and torso toward the wall and throw the ball against it.</li><li><strong>Return:</strong> Catch the ball on the rebound and repeat.</li></ul>" },
                { name: "Mountain Climbers", sets: "3", reps: "20 total", cues: "<ul class='list-disc list-inside space-y-2'><li><strong>Setup:</strong> Start in a high plank position.</li><li><strong>Execution:</strong> Keeping your core tight and back flat, drive one knee towards your chest, then quickly switch and drive the other knee in. The movement should look like you are running in place in a plank position.</li></ul>" },
            ],
            cooldown: "Focus on mobility and any weak points identified during training."
        },
        7: { title: "Rest Day", warmup: "", exercises: [], cooldown: "Active recovery. Focus on mobility, light cardio (walking), hydration, and nutrition. Allow your body to fully recover and adapt." },
    },
};